[package]
name = "rust_bvgsdk_experiment"
version = "0.0.2"
authors = ["ornse01 <ornse01@users.osdn.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
